apply plugin: 'com.android.application'

android {
    namespace = "com.example.cocotrade"
    compileSdk = 34

    defaultConfig {
        applicationId "com.example.cocotrade"
        minSdkVersion 23
        targetSdkVersion 34
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

        // Access the API Secret from local.properties or Env
        def localProperties = new Properties()
        def localPropertiesFile = rootProject.file('local.properties')
        if (localPropertiesFile.exists()) {
            localProperties.load(new FileInputStream(localPropertiesFile))
        }
        def cloudinarySecret = localProperties.getProperty('CLOUDINARY_API_SECRET') ?: System.getenv("CLOUDINARY_API_SECRET") ?: ""
        buildConfigField "String", "CLOUDINARY_API_SECRET", "\"${cloudinarySecret}\""
    }

    signingConfigs {
        config {
            // Use custom keystore if available, otherwise fallback to default
            def keystoreFile = file('permanent_debug.keystore')
            if (keystoreFile.exists()) {
                storeFile keystoreFile
                storePassword 'android'
                keyAlias 'androiddebugkey'
                keyPassword 'android'
            }
        }
    }

    buildFeatures {
        buildConfig = true
    }

    buildTypes {
        debug {
            if (signingConfigs.config.storeFile != null) {
                signingConfig signingConfigs.config
            }
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            if (signingConfigs.config.storeFile != null) {
                signingConfig signingConfigs.config
            }
        }
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation "androidx.appcompat:appcompat:1.7.0"
    implementation "com.google.android.material:material:1.12.0"
    implementation "androidx.constraintlayout:constraintlayout:2.1.4"
    implementation "androidx.fragment:fragment:1.8.1"

    // Firebase BoM, Auth and Realtime Database
    implementation platform('com.google.firebase:firebase-bom:33.1.2')
    implementation 'com.google.firebase:firebase-auth'
    implementation 'com.google.firebase:firebase-database'

    // Cloudinary Android SDK
    implementation 'com.cloudinary:cloudinary-android:3.0.2'

    // Glide for image loading
    implementation 'com.github.bumptech.glide:glide:4.16.0'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.16.0'

    // Google Play Services Auth
    implementation 'com.google.android.gms:play-services-auth:21.2.0'

    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'
}

apply plugin: 'com.google.gms.google-services'
